### ISSUE TITLE
Crouch input detection needs to be less sensitive on gamepad

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#160]
### When reporting a bug/issue:
- Fantasy Crescendo Version: 0.3.0-alpha dev build #255
- Operating System: Windows 10 64-bit
- Expected Behavior: Character shouldn't crouch with an imperfect horizontal directional input.  I think this should be about 30 degrees above/below the x-axis, maybe more.
- Actual Behavior: Character crouches if the input is even slightly below horizontal.
- Steps to reproduce the behavior:
  0. With a gamepad, make a left/right directional input once you've loaded in on a stage.

**Comment by james7132** [comment]
This seems to be because all directional input has a lower threshold of (-0.1, 0.1) in a control axis range of (-1.0, 1.0). 

There is also the issue that it is a "square" threshold, where the line dividing moving left and moving right takes precedence so long as their conditions are met before the downward movement is.

We'll need to redo our directional input logic for state transitions.

**Comment by james7132** [comment]
@pzhang87 this should have been resolved in d8855c7e952ff450ecdfc88b33e213d16d5356be. Does this seem to resolve the issue?

**Comment by james7132** [comment]
This seems to be resolved as of now.
